language: node_js

node_js:
  - iojs

cache:
  timeout: 1000
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm i
  - npm run test:coverage

after_success:
  - npm run push-codacy-coverage
